BINDING_HEADER_ClassicLFR = LFG_TITLE:gsub(" ","")
BINDING_NAME_ClassicLFR_show_hide = SHOW..'/'..HIDE
BINDING_NAME_ACCEPT = ACCEPT
BINDING_NAME_CANCEL = CANCEL
BINDING_NAME_START_A_GROUP = START_A_GROUP
BINDING_NAME_LFG_LIST_SEARCH_AGAIN = LFG_LIST_SEARCH_AGAIN
BINDING_NAME_INVITE = INVITE
BINDING_NAME_DECLINE = DECLINE
